### ISSUE TITLE
Visual Studio 17.7.2 breaks AeroWizard

### ISSUE THREAD

**Issue by rrirower** [dahall/AeroWizard#100]
I updated my Visual Studio 2022 to 17.7.2.  It appears this update broke AeroWizard because several controls in the toolbox are now disabled.  I can add controls to any form that does not have a wizard control. If I try to add a control to a wizard form I see the following:

![Capture](https://github.com/dahall/AeroWizard/assets/34550407/8279442c-cad3-4d09-b3be-6b76568dd152)

**Comment by rrirower** [comment]
Reverting Visual Studio back to 17.6.3 seems to resolve this issue.

**Comment by a-einstein** [comment]
I may be struggling with the same issue, in a worse form.
Editing WizardPages does not work at all.

I am currently on AeroWizard 2.3.1, VisualStudio 17.8.2, and .net 6.
I am trying AeroWizard, which looked promising.

I have installed the Nuget package and got the controls automatically added to the toolbox.
I have created a Form, added WizardControl, added 2 WizardPages.
When I select a WizardPage, I have NO controls in the toolbox to add.

As a workaround I added a Label to WizardControl, then manually edited it to be contained in a WizardPage.
I did this for both WizardPages.
This somewhat works, I could see both WizardPages with their Labels, but this is no workable solution.

I have tried this in  VisualStudio 2019 as well. It got somewhat better, with controls in the toolbox.
But I could only edit the first WizardPage. The Document Outline does not see anything below the WizardControl.
It is not desirable anyway to be forced to a different VisualStudio.

Please react to this issue.
And hopefully fix it soon. I would have to abandon this otherwise.

**Comment by a-einstein** [comment]
Update.

By putting the WizardPage in a UserControl I was able to edit it.
It is not in the toolbox, so that demanded some hacking.

Then by making the WizardPage accessible by a property, I could add it to WizardControl.Pages.

All in VisualStudio  2022 again.

This seems workable, but definitely is just a workaround.

Other remark.
The API Documentation particularly looks fine.
But what I lack is a complete working code example. 
I still don’t know when or how to apply controls like WizardPageContainer.

**Comment by rrirower** [comment]
@a-einstein fyi...I ended up removing aerowizard and creating my own wizard with panels.

**Comment by dontbyte** [comment]
> All in VisualStudio 2022 again.

Probably more a .NET issue: https://github.com/dahall/AeroWizard/issues/92  https://github.com/dahall/AeroWizard/issues/93
Did you find a better solution?

**Comment by rrirower** [comment]
@dontbyte I was forced to abandon this project.  I "rolled my own" wizard code.
